tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#52358b",
        "outline": "#968d9e",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "background": "#131313",
        "on-secondary-container": "#c3a6ff",
        "on-primary-fixed": "#270057",
        "secondary": "#d2bbff",
        "on-tertiary-fixed-variant": "#49454f",
        "tertiary": "#cbc4d1",
        "surface-container-highest": "#353534",
        "surface-container": "#201f1f",
        "surface": "#131313",
        "secondary-fixed-dim": "#d2bbff",
        "on-tertiary": "#322f38",
        "on-primary-fixed-variant": "#5b20ab",
        "primary-fixed-dim": "#d5baff",
        "inverse-primary": "#743fc4",
        "on-tertiary-container": "#c4bdca",
        "on-surface": "#e5e2e1",
        "on-primary": "#42008a",
        "surface-tint": "#d5baff",
        "on-surface-variant": "#cdc3d5",
        "error": "#ffb4ab",
        "primary": "#d5baff",
        "tertiary-fixed": "#e7e0ed",
        "tertiary-fixed-dim": "#cbc4d1",
        "tertiary-container": "#504c57",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#eaddff",
        "on-secondary-fixed": "#25005a",
        "inverse-surface": "#e5e2e1",
        "primary-fixed": "#ecdcff",
        "inverse-on-surface": "#313030",
        "on-secondary": "#3b1c73",
        "on-primary-container": "#d0b2ff",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#52358b",
        "on-background": "#e5e2e1",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "on-tertiary-fixed": "#1d1a23",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#632bb3",
        "outline-variant": "#4a4453",
        "on-error": "#690005"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "card-padding": "32px",
        "margin": "40px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["Space Grotesk"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
}